#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EyesOn.UI.Droid.Resource", IsApplication=true)]

namespace EyesOn.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int camera_id = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int show_fps = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000e
			public const int CameraView = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int TransparentView = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int any = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int back = 2131230721;
			
			// aapt resource value: 0x7f080012
			public const int calibrate = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int calibration = 2131230740;
			
			// aapt resource value: 0x7f08000a
			public const int cameraCalibration = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int cameraControl = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int cameraPreview = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int camera_calibration_java_surface_view = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int colorBlobDetection = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int color_blob_detection_activity_surface_view = 2131230725;
			
			// aapt resource value: 0x7f080016
			public const int comparison = 2131230742;
			
			// aapt resource value: 0x7f080006
			public const int fd_activity_surface_view = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int front = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int image_manipulations_activity_surface_view = 2131230727;
			
			// aapt resource value: 0x7f080013
			public const int preview_mode = 2131230739;
			
			// aapt resource value: 0x7f08000d
			public const int scrollView1 = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int surfaceView = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public const int takePhoto = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int tutorial2_activity_surface_view = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int tutorial3_activity_java_surface_view = 2131230737;
			
			// aapt resource value: 0x7f080015
			public const int undistortion = 2131230741;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int camera_calibration_surface_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CameraPreview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int color_blob_detection_surface_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int face_detect_surface_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int haarcascade_frontalface_default = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int image_manipulations_surface_view = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Puzzle = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int take_photo_surface_view = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int tutorial2_surface_view = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int tutorial3_surface_view = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int calibration = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int haarcascade_eye = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int haarcascade_frontalface_alt = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int haarcascade_frontalface_alt_tree = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int lbpcascade_frontalface = 2131034115;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int action_calibrate = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int calibrating = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int calibration = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int calibration_successful = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int calibration_unsuccessful = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int comparison = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int more_samples = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int original = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int please_wait = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int preview_mode = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int undistorted = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int undistortion = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int haarcascade_eye = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int haarcascade_frontalface_alt = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int haarcascade_frontalface_alt2 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int haarcascade_frontalface_alt_tree = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int haarcascade_frontalface_default = 2130968580;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
